title: Errata for PDF specifications
encoding: UTF-8
author:
  name: "PDF Association"
  email: info@pdfa.com

description: >- # this means to ignore newlines until "baseurl:"
  Industry-agreed resolutions for errata reported against PDF standards and specifications.

tagline: Resolutions to PDF specification errata

baseurl: /
url: https://pdf-issues.pdfa.org
logo: ./assets/PDFa-logo-black-text.png
favicon_ico: ./favicon.png

theme: just-the-docs
layout: default
color_scheme: light # or dark

# Aux. Links appear in the top right corner.
aux_links_new_tab: true
aux_links:
  PDF Association: https://pdfa.org/
  Github: https://github.com/pdf-association/pdf-issues

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# HTML compression must be disabled so line-breaks in code samples are preserved.
compress_html:
  ignore:
    envs: all

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag

# See: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
social:
  name: PDF Association
  links:
    - https://www.linkedin.com/company/pdf-association/
    - https://github.com/pdf-association/
    - https://www.youtube.com/ThePDFAssociation
    - https://www.facebook.com/PDFassociation


# See https://github.com/jekyll/minima
google_analytics: G-F90FBHNRDT

# Sidebar navigation
nav_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Enable or disable the site search
search_enabled: true
search:
  # Split pages into sections that can be searched individually. Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result. Default: 3
  previews: 5
  # Maximum amount of words to display before a matched word in the preview. Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview. Default: 10
  preview_words_after: 10
  # Set the search token separator. Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

enable_copy_code_button: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
